Repository Heuristic-Hex-Hack/Ds-Algo-ML, pull requests merged in 2020-10, with the labels that each got.

#3 Change in Maintainer section
  README.md
Labels: enhancement, hacktoberfest-accepted

#26 Added infix to postfix in C
  C/DS/stack/infixtopostfix.c
Labels: enhancement, good first issue, hacktoberfest-accepted

#28 #9 Linear Search in C++
  C++/Algo/Searching/Linear Searching.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#27 Overloading of binary operator
  Binary_overloading.cpp
  Dynamic_memory_allocation_eg.cpp
Labels: hacktoberfest-accepted
